### ISSUE TITLE
Module not found: Can't resolve 'assets/css/app.css' in '/Users/Neutron/Product/Profile/src'

### ISSUE THREAD

**Issue by codevjs** [itsfaqih/fama#1]
![image](https://user-images.githubusercontent.com/48341107/103534207-6bdd7280-4ec9-11eb-8866-7ca8fc94b05c.png)

**Comment by itsfaqih** [comment]
Hi, thanks for opening the issue.
app.css is only exist after compiling the tailwind css, have you tried to run the `npm run watch:style` or `npm run build:style` before?

**Comment by codevjs** [comment]
no, i just run the yarn install and yarn start

**Comment by itsfaqih** [comment]
Try to run `yarn watch:style` or `yarn build:style`

**Comment by codevjs** [comment]
okay, its work thanks
